[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "limnoria-mem"
version = "1.0.0"
authors = [
    { name = "Barry Suridge" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "limnoria",
    "psutil",
]
classifiers = [
    'Environment :: Plugins',
    'Programming Language :: Python :: 3',
    'Topic :: Communications :: Chat',
]

[project.entry-points.'limnoria.plugins']
Mem = "limnoria_mem"

[tool.black]
line-length = 79
target-version = ["py311"]
extend-exclude = '''
/(
    backup
  | conf
  | data
  | logs
  | tmp
  | __pycache__
  | \.pytest_cache
)/
'''

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
explicit_package_bases = true
exclude = "(__init__|test)\\.py"

[tool.pytest.ini_options]
python_files = ["test.py"]

[tool.setuptools.package-dir]
"limnoria_mem" = "."
"limnoria_mem.local" = "local/"

[tool.setuptools.package-data]
"limnoria_mem" = ["locales/*.po"]
